version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: emprestimos-app:latest
    container_name: emprestimos-app
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/var/www/html
      - storage_data:/var/www/html/storage
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: emprestimos-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: emprestimos-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  storage_data:
